### ISSUE TITLE
osc-cloud-controller-manager pod CrashLoopBackOff

### ISSUE THREAD

**Issue by dleborgne** [outscale-dev/cloud-provider-osc#58] opened 2022-01-18 14:25 UTC
**What happened**:
I'm trying to setup a Kubernetes cluster (3 worker nodes, 3 control plane nodes) on OUTSCALE cloudgouv-eu-west-1 using github.com/jerome-jutteau/kubernetes-with-rke. During the cluster initialization, the osc-cloud-controller-manager pods fail and the `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` taints remain.

**What you expected to happen**:
Taint `node.cloudprovier.kubernetes.io/uninitialized=True:NoSchedule` removed on nodes.

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/jerome-jutteau/kubernetes-with-rke
# edit access_key_id, secret_key_id and region in terraform.tfvars
terraform init
terraform apply
rke up --config rke/cluster.yml
```

**Anything else we need to know?**:
In the osc-cloud-controller-manager log, the last HTTP request gets an HTTP 400. Can the odd User-Agent explain this error ? 
```
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: fcu.cloudgouv-eu-west-1.outscale.com
User-Agent: kubernetes/v0.0.0-master+$Format:%H$ aws-sdk-go/1.40.46 (go1.15.6; linux; amd64)
Content-Length: 67
Authorization: AWS4-HMAC-SHA256 Credential=[...]/20220118/cloudgouv-eu-west-1/ec2/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=5d1[...]a81
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20220118T115904Z
Accept-Encoding: gzip

Action=DescribeInstances&InstanceId.1=i-9e473968&Version=2016-11-15
-----------------------------------------------------
I0118 11:59:04.430436       1 log_handler.go:34] AWS API Send: ec2 DescribeInstances &{DescribeInstances POST / 0xc00004cd20 <nil>} {
  InstanceIds: ["i-9e473968"]
}
I0118 11:59:04.430527       1 log_handler.go:39] AWS API ValidateResponse: ec2 DescribeInstances &{DescribeInstances POST / 0xc00004cd20 <nil>} {
  InstanceIds: ["i-9e473968"]
} 400 Bad Request
2022/01/18 11:59:04 DEBUG: Response ec2/DescribeInstances Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Content-Length: 266
Connection: keep-alive
Content-Type: text/xml;charset=UTF-8
Date: Tue, 18 Jan 2022 11:59:04 GMT
Server: nginx
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.6
- Cloud provider or hardware configuration: OUTSCALE
- OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS
- Kernel (e.g. `uname -a`): 5.4.0-91-generic

/kind bug

**Comment by jerome-jutteau** [comment] 2022-01-19 08:55
Hi @dleborgne,

Thanks for reaching us, we are looking at your issue

**Comment by jerome-jutteau** [comment] 2022-01-19 11:37
Nice that you have already found our initial work around rke. FYI we have migrated it to [outscale-dev/osc-k8s-rke-cluster](https://github.com/outscale-dev/osc-k8s-rke-cluster/) as we now have several people working on it.

This is still work in progress but we are glade to help you with it.

Having `NoSchedule` taint on all node is [expected](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/) at least on initialization phase and should be removed once ready after few seconds.

We were able to reproduce your issue and a different region. It was occurring because some region names were hard coded to `eu-west-2` in this older branch. This should now be fixed on [outscale-dev/osc-k8s-rke-cluster](https://github.com/outscale-dev/osc-k8s-rke-cluster/).

Also, as you are on gouvcloud platform, be aware that [API Access Rules](https://docs.outscale.com/en/userguide/About-API-Access-Rules.html) _may_ block CCM to perform API calls due to its source IP.

**Comment by dleborgne** [comment] 2022-01-19 13:14
Thank you @jerome-jutteau for your answer. I'll give a try to the new [outscale-dev/osc-k8s-rke-cluster](https://github.com/outscale-dev/osc-k8s-rke-cluster/). Glad to hear that this project is gaining more support !

I have to mention that I had the hard-coded `eu-west-2` [already fixed](https://github.com/dleborgne/kubernetes-with-rke/commit/ce8b083290fc1075e9be073a2cbbc3fac466ad36) in a fork from jerome-jutteau/kubernetes-with-rke before I encountered the problem described here. I'll let you know quickly if things are getting better with outscale-dev/osc-k8s-rke-cluster.

Thanks also for pointing out the API Access Rules, I'll take a look.

**Comment by dleborgne** [comment] 2022-01-19 22:12
API Access Rules were responsible for the CCM initialization failure ! Adding the cluster "nat" IP address in authorized IP addresses with CreateApiAccessRule fixed the issue. Thank you for pointing out this cloudgov platform behavior.

**Closed** 2022-01-20 08:34 UTC
